export const CIUDADES_POR_DEPARTAMENTO = {
  'Amazonas': ['Leticia'],
  'Antioquia': ['Medellín', 'Apartadó', 'Bello', 'Caucasia', 'Envigado', 'Itagüí', 'Rionegro', 'Turbo'],
  'Arauca': ['Arauca'],
  'Atlántico': ['Barranquilla', 'Malambo', 'Soledad'],
  'Bogotá D.C.': ['Bogotá'],
  'Bolívar': ['Cartagena', 'Magangué'],
  'Boyacá': ['Duitama', 'Sogamoso', 'Tunja'],
  'Caldas': ['Chinchiná', 'Manizales'],
  'Caquetá': ['Florencia'],
  'Casanare': ['Yopal'],
  'Cauca': ['Popayán'],
  'Cesar': ['Valledupar'],
  'Chocó': ['Quibdó'],
  'Córdoba': ['Lorica', 'Montería'],
  'Cundinamarca': ['Chía', 'Facatativá', 'Fusagasugá', 'Soacha', 'Zipaquirá'],
  'Guainía': ['Inírida'],
  'Guaviare': ['San José del Guaviare'],
  'Huila': ['Neiva', 'Pitalito'],
  'La Guajira': ['Maicao', 'Riohacha'],
  'Magdalena': ['Ciénaga', 'Santa Marta'],
  'Meta': ['Acacías', 'Villavicencio'],
  'Nariño': ['Pasto', 'Tumaco'],
  'Norte de Santander': ['Cúcuta', 'Ocaña'],
  'Putumayo': ['Mocoa'],
  'Quindío': ['Armenia'],
  'Risaralda': ['Dosquebradas', 'Pereira'],
  'San Andrés y Providencia': ['San Andrés'],
  'Santander': ['Barrancabermeja', 'Bucaramanga', 'Floridablanca', 'Girón'],
  'Sucre': ['Sincelejo'],
  'Tolima': ['Espinal', 'Ibagué'],
  'Valle del Cauca': ['Buenaventura', 'Buga', 'Cali', 'Cartago', 'Palmira', 'Tuluá'],
  'Vaupés': ['Mitú'],
  'Vichada': ['Puerto Carreño'],
};

export const DEPARTAMENTOS = Object.keys(CIUDADES_POR_DEPARTAMENTO);
